# Basic site settings
title: Panda Express Docs
description: Documentation for Kiosk and Manager apps
theme: jekyll-theme-slate
url: "https://csce331-team-5p.github.io/Project_3" # Update with your GitHub Pages URL

# Options for navigation, layout, and more
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
