
title: Panda Express Docs
description: Documentation for Kiosk and Manager apps
theme: jekyll-theme-slate
url: "https://csce331-team-5p.github.io/Project_3"
baseurl: "/Project_3" 
source: docs


markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
