# Basic site settings
title: Panda Express Docs
description: Documentation for Kiosk and Manager apps
theme: jekyll-theme-cayman # Change this to your desired theme
url: "https://yourusername.github.io" # Update with your GitHub Pages URL

# Options for navigation, layout, and more
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed
