import "./globals.css";
// import { OrderProvider } from '@/context/OrderContext';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
        {/* <OrderProvider>{children}</OrderProvider> */}
      </body>
    </html>
  );
}
