import "./globals.css";
import { GlobalStateProvider } from "@/components/GlobalStateProvider";
import { MagnifierProvider } from "@/context/MagnifierContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalStateProvider>
          <MagnifierProvider>{children}</MagnifierProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}
