import "./globals.css";
// import { OrderProvider } from '@/context/OrderContext';
import { GlobalStateProvider } from "@/components/GlobalStateProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`} >
        <GlobalStateProvider>
          {children}
        </GlobalStateProvider>
        {/* <OrderProvider>{children}</OrderProvider> */}
      </body>
    </html>
  );
}
